[package]
name = "dataserver"
version = "0.1.0"
authors = ["David Kleingeld <dskleingeld@gmail.com>"]

[dependencies]
websocket = "0.20.3"
native-tls = "^0.1.2"

actix-web = { version = "0.7.7", features = ["alpn"] }
openssl = "^0.10"
actix = "0.7.4"

env_logger = "0.5.13"
