[package]
name = "dataserver"
version = "0.2.0"
authors = ["David Kleingeld <dskleingeld@gmail.com>"]
edition = "2018"
publish = false

[features]
plotting = ["plotters", "image"]

[dependencies]
structopt = "0.3"

actix-web = { version = "1.0.3", features = ["rust-tls"] }
actix-web-actors = "1.0.2"
actix-net = "0.2.4"
actix-identity = "0.1.0"
actix-files = "0.1.3"
actix-rt = "0.2.4"
actix-service = "0.4.1"
#temporary override of indirect dependency as 69.2 is not semver compatible
onig_sys= "=69.1.0" 

yarte = { version ="0.3.2", features=["with-actix-web"]  }

sled = "0.24.1"

rustls = "0.15.0"
ring = "0.14.6"

actix = "0.8.3"
futures = "0.1.28"
bytes = "0.4.12"
walkdir = "2.2.5"
num = "0.2.0"

#acme-client = "0.5.3" replaced with patched version that fixes openssl issues
acme-client = { git = "https://github.com/janderholm/acme-client"}

webpki = "0.19.1"
webpki-roots = "0.16.0"
untrusted = "0.6.2"

chrono = { version = "0.4.6", features = ["serde"] }
rand = "0.5.5"

log = "0.4.5"
fern = { version = "0.5.6", features = ["colored"] }

bincode = "1.0.1"
text_io = "0.1.7"

serde_derive = "1.0.80"
serde = "1.0.80"
serde_yaml = "0.8.7"
serde_json = "1.0.33"

#for testing
reqwest = "=0.9.17" #pinned to old version until ascync await is her
byteorder = "1.2.6"

#minimal_timeseries = { path = "../minimal_timeseries" }
minimal_timeseries = { git = "https://github.com/dskleingeld/minimal_timeseries", branch = "multithraeded_file_read" }

smallvec = "0.6.6"
crossbeam-utils = "0.6"

num-traits = "0.2"
num-derive = "0.2"

telegram-bot = "0.6"

plotters = { version = "0.2", optional = true }
image = { version = "0.2", optional = true }