[package]
name = "dataserver"
version = "0.3.0"
authors = ["David Kleingeld <dskleingeld@gmail.com>"]
edition = "2018"
publish = false

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

panic = 'unwind'
debug = true
debug-assertions = true
overflow-checks = true

[features]
plotting = ["plotters", "image"]
stable = []

[dependencies]
structopt = "0.3"
dialoguer = "0.5.0"
console = "0.9.1"

actix = "0.9"
actix-rt = "1.0"
#async-std = "1.4.0"
futures = "0.3.1"
actix-web = { version = "2", features = ["rustls"] }
actix-web-actors = "2"
actix-net = "0.2.6"
actix-identity = "0.2.0"
actix-files = "0.2.1"
actix-service = "1.0.1"
yarte = { version ="0.5", features=["with-actix-web"] }
#temporary override of indirect dependency as 69.2 is not semver compatible
onig_sys= "=69.1.0" 

sled = "0.30"

rustls = "0.16.0"
ring = "0.16.9"

bytes = "0.5"
walkdir = "2.2.5"
num = "0.2.0"
threadpool = "1.7.1"

cert_tools = { git = "https://github.com/dskleingeld/cert_manager" }

webpki = "0.21"
webpki-roots = "0.18.0"
untrusted = "0.6.2"

chrono = { version = "0.4.6", features = ["serde"] }
rand = "0.5.5"

log = "0.4.5"
fern = { version = "0.5.6", features = ["colored"] }

bincode = "1.0.1"
text_io = "0.1.7"

serde_derive = "1.0.80"
serde = "1.0.80"
serde_yaml = "0.8.7"
serde_json = "1.0.33"

reqwest = {version = "0.10.0", features = ["blocking"]}
byteorder = "1.2.6"

#minimal_timeseries = { path = "../minimal_timeseries" }
minimal_timeseries = { git = "https://github.com/dskleingeld/minimal_timeseries", branch = "multithraeded_file_read" }

smallvec = "0.6.6"
crossbeam-utils = "0.6"
itertools = "0.8.2"

num-traits = "0.2"
num-derive = "0.2"

telegram-bot = "0.6"

#servo-fontconfig-sys = { git = "https://github.com/dskleingeld/libfontconfig" }
plotters = { version = "0.2", optional = true}
#plotters = { version = "0.2", optional = true, default-features = false, features = ["bitmap", "datetime"]}
image = { version = "0.22", optional = true }
evalexpr = "5.0.5"
regex = "1.3"

#[replace]
#"servo-fontconfig-sys:4.0.6#servo-fontconfig-sys:4.0.9" = { git = "https://github.com/dskleingeld/libfontconfig" }